### ISSUE TITLE
IPythonViz no longer functioning

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo_gui#325]
(It'd probably be best to rename this IPythonGUI... and this might have something to do with renaming?). 
When I use it, I get:

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/celiasmi/Documents/nengo/nengo_gui/nengo_gui/viz.py", line 350, in begin_lifecycle
    server, interactive=self.interactive)
  File "/Users/celiasmi/Documents/nengo/nengo_gui/nengo_gui/swi.py", line 436, in begin_lifecycle
    signal.signal(signal.SIGINT, cls._immediate_shutdown)
ValueError: signal only works in main thread

**Comment by jgosmann** [comment]
Unrelated to the renaming. We need unit tests ... each merge is breaking something else because things interact in too many ways.

**Comment by jgosmann** [comment]
Use the `fix-ipythonviz` branch until merged.

**Comment by celiasmith** [comment]
Thanks! :smiley:

**Comment by tcstewar** [comment]
> We need unit tests ... each merge is breaking something else because things interact in too many ways.

+1 +1 +1 +1 +1
