### ISSUE TITLE
Starting up nengo_gui with local locals() causes an error.

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo_gui#358]
If you try to start nengo_gui and pass in local variables to the initialization call (like so: 
```python
...
nengo_gui.viz.Viz(__file__, model=model, locals=locals()).start()
```

the following error occurs:
```Starting nengo_gui server at http://localhost:8080
Traceback (most recent call last):
  File "d:\fchoo\documents\github\nengo_gui\nengo_gui\swi.py", line 276, in hand
le_request
    text = getattr(self, command)(*args[1:], **db)
  File "d:\fchoo\documents\github\nengo_gui\nengo_gui\server.py", line 85, in sw
i
    viz_sim = self.server.viz.create_sim()
  File "d:\fchoo\documents\github\nengo_gui\nengo_gui\viz.py", line 394, in crea
te_sim
    viz_sim = VizSim(self)
  File "d:\fchoo\documents\github\nengo_gui\nengo_gui\viz.py", line 47, in __ini
t__
    self.add_template(template)
  File "d:\fchoo\documents\github\nengo_gui\nengo_gui\viz.py", line 73, in add_t
emplate
    c = template.create(self)
  File "d:\fchoo\documents\github\nengo_gui\nengo_gui\components\component.py",
line 37, in create
    *self.args, **self.kwargs)
  File "d:\fchoo\documents\github\nengo_gui\nengo_gui\components\ace_editor.py",
 line 11, in __init__
    self.current_code = self.viz.viz.code
AttributeError: 'Viz' object has no attribute 'code'```

Looking at the code in ```load``` function in ```nengo_gui/viz.py```, it looks like when you provide the locals variable, the block of code that initializes the ```code``` attribute in the ```viz``` object is skipped over entirely (lines 205 to 212).  

This problem can be skirted by setting ```interactive=False``` in the ```Viz``` object constructor.

**Comment by tcstewar** [comment]
This still seems to be the case, but with a wacky new error:

```
Starting nengo server at http://localhost:8080
ERROR:nengo_gui.server:Error response
Traceback (most recent call last):
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\server.py", line 233, in do_GET
    self.handle_upgrade()
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\server.py", line 260, in handle_upgrade
    self.upgrade_to_ws()
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\server.py", line 306, in upgrade_to_ws
    self.ws_default()
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\guibackend.py", line 92, in auth_checked
    return fn(inst)
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\guibackend.py", line 230, in ws_default
    component.update_client(self.ws)
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\components\netgraph.py", line 389, in update_client
    self.send_pan_and_zoom(client)
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\components\netgraph.py", line 572, in send_pan_and_zoom
    pan = self.page.config[self.page.model].pos
  File "c:\users\terry\documents\github\nengo\nengo\config.py", line 344, in __getitem__
    "configures('%(name)s') first." % {'name': type(key).__name__})
ConfigError: Type 'NoneType' is not set up for configuration. Call configures('NoneType') first.
```
