### ISSUE TITLE
Reload falls over

### ISSUE THREAD

**Issue by mundya** [nengo/nengo_gui#381]
I tried to reload the model I was using in #371.  When I do the browser displays:

```
Traceback (most recent call last):
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/swi.py", line 276, in handle_request
    text = getattr(self, command)(*args[1:], **db)
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/server.py", line 80, in swi
    reset=True)
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/viz.py", line 252, in load
    self.name_finder = nengo_gui.NameFinder(locals, model)
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/namefinder.py", line 13, in __init__
    self.find_names(net)
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/namefinder.py", line 16, in find_names
    net_name = self.known_name[net]
KeyError: 
```

The same occurs for Python 2 (installed from Pip)

```
Traceback (most recent call last):
  File "/tmp/test_gui/lib/python2.7/site-packages/nengo_gui/swi.py", line 276, in handle_request
    text = getattr(self, command)(*args[1:], **db)
  File "/tmp/test_gui/lib/python2.7/site-packages/nengo_gui/server.py", line 80, in swi
    reset=True)
  File "/tmp/test_gui/lib/python2.7/site-packages/nengo_gui/viz.py", line 252, in load
    self.name_finder = nengo_gui.NameFinder(locals, model)
  File "/tmp/test_gui/lib/python2.7/site-packages/nengo_gui/namefinder.py", line 13, in __init__
    self.find_names(net)
  File "/tmp/test_gui/lib/python2.7/site-packages/nengo_gui/namefinder.py", line 16, in find_names
    net_name = self.known_name[net]
KeyError: 
```

**Comment by mundya** [comment]
Usefully the browser doesn't get the full traceback: the missing key is....
`<Network (unlabelled) at ...>`

**Comment by tcstewar** [comment]
Weird.  what happens on a browser reload?  Can you post the .py and .py.cfg files?

**Comment by mundya** [comment]
On further playing this only occurs if the file you have open was created by the GUI.

To reproduce:
 1. `nengo_gui this_file_does_not_exist.py`
 2. Add something to the network
 3. Click "Reload" [Reloading the browser does not do this!]

**Comment by tcstewar** [comment]
> Click "Reload"

We really need to change the icon for that button.  It's not meant to be thought of as a reload -- it's meant to be a "reset", but it's so close to the reload idea (and icon) that I keep getting confused between them.
