### ISSUE TITLE
Crash on probing passthrough nodes

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo_gui#393]
When I probe the passthrough nodes (input or output) in sequence_routed.py, I get:

Traceback (most recent call last):
  File "/Users/celiasmi/Documents/nengo/nengo_gui/nengo_gui/swi.py", line 237, in handle_ws_request
    getattr(self, command)(*[client] + args[1:], **db)
  File "/Users/celiasmi/Documents/nengo/nengo_gui/nengo_gui/server.py", line 144, in ws_viz_component
    component.message(msg)
  File "/Users/celiasmi/Documents/nengo/nengo_gui/nengo_gui/components/netgraph.py", line 269, in message
    act = create_action(action, self, **info)
  File "/Users/celiasmi/Documents/nengo/nengo_gui/nengo_gui/components/action.py", line 12, in create_action
    return CreateGraph(net_graph, **kwargs)
  File "/Users/celiasmi/Documents/nengo/nengo_gui/nengo_gui/components/action.py", line 140, in __init__
    self.act_create_graph()
  File "/Users/celiasmi/Documents/nengo/nengo_gui/nengo_gui/components/action.py", line 158, in act_create_graph
    self.send('js', code=c.javascript())
  File "/Users/celiasmi/Documents/nengo/nengo_gui/nengo_gui/components/value.py", line 40, in javascript
    json = self.javascript_config(info)
  File "/Users/celiasmi/Documents/nengo/nengo_gui/nengo_gui/components/component.py", line 25, in javascript_config
    return json.dumps(cfg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: 16 is not JSON serializable

**Comment by tcstewar** [comment]
Argh, that's this bug again:

https://github.com/nengo/nengo_gui/blob/master/nengo_gui/components/value.py#L16

here's the line:

```self.n_lines = obj.size_out```

Basically, on some versions of numpy, obj.size_out isn't serializable.  It's a zero-order array rather than an int.  I thought I'd gone through the code and changed them to ```int(obj.size_out)``` but clearly not...
