### ISSUE TITLE
Infinite loop catching 10053 error

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo_gui#418]
I sometimes get an infinite list of errors when closing nengo_gui on Windows:

```
error: [Errno 10053] An established connection was aborted by the software in your host machine
Traceback (most recent call last):
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\server.py", line 125, in ws_viz_component
    msg = client.read()
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\swi.py", line 594, in read
    data = data + bytearray(self.socket.recv(512))
error: [Errno 10053] An established connection was aborted by the software in your host machine
Traceback (most recent call last):
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\server.py", line 125, in ws_viz_component
    msg = client.read()
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\swi.py", line 594, in read
    data = data + bytearray(self.socket.recv(512))
error: [Errno 10053] An established connection was aborted by the software in your host machine
Traceback (most recent call last):
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\server.py", line 125, in ws_viz_component
    msg = client.read()
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\swi.py", line 594, in read
    data = data + bytearray(self.socket.recv(512))
```

**Comment by jgosmann** [comment]
How are you closing it? By closing the browser window or by interrupting it on the console?

**Comment by tcstewar** [comment]
I think it was by interrupting it on the console, but I don't quite remember.  I've only had it happen twice.

**Comment by jgosmann** [comment]
Probably an `SocketClosedError` should be raised for this error code [here](https://github.com/nengo/nengo_gui/blob/master/nengo_gui/swi.py#L595)
