### ISSUE TITLE
Permission denied when using the cache with nengo_gui

### ISSUE THREAD

**Issue by bjkomer** [nengo/nengo_gui#419]
I had a model with the network seed set that I ran with nengo_gui. When I clicked play in the gui, it seemed to hang for a while with the gear spinning, and I noticed this error on my console:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/bjkomer/nengo_gui/nengo_gui/viz.py", line 129, in runner
    self.build()
  File "/home/bjkomer/nengo_gui/nengo_gui/viz.py", line 98, in build
    self.sim = backend.Simulator(self.model)
  File "/home/bjkomer/nengo/nengo/simulator.py", line 111, in __init__
    self.model.build(network)
  File "/home/bjkomer/nengo/nengo/builder/builder.py", line 34, in build
    return Builder.build(self, *objs)
  File "/home/bjkomer/nengo/nengo/builder/builder.py", line 74, in build
    cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/home/bjkomer/nengo/nengo/builder/network.py", line 63, in build_network
    model.build(conn)
  File "/home/bjkomer/nengo/nengo/builder/builder.py", line 34, in build
    return Builder.build(self, *objs)
  File "/home/bjkomer/nengo/nengo/builder/builder.py", line 74, in build
    cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/home/bjkomer/nengo/nengo/builder/connection.py", line 121, in build_connection
    decoders, solver_info = solver(activities, targets, rng=rng)
  File "/home/bjkomer/nengo/nengo/cache.py", line 254, in cached_solver
    with open(path, 'wb') as f:
IOError: [Errno 13] Permission denied: '/home/bjkomer/.cache/nengo/decoders/6c/9576f88958b7dd3a758d3ea7a409c9f264e92c.nco'
```

I ended up having to restart it to get it to work. I always set the seed in my networks and haven't ran into this before now.

**Comment by tcstewar** [comment]
Any chance you ran your model with sudo at some point?

**Comment by jgosmann** [comment]
What are the permissions of `/home/bjkomer/.cache/nengo/decoders/6c/9576f88958b7dd3a758d3ea7a409c9f264e92c.nco` and the folder it's in?

**Comment by jgosmann** [comment]
And which user owns the file and folder?

**Comment by bjkomer** [comment]
The permissions for the folder: `drwxr-xr-x` and file: `-rw-r--r--`
The owner of both is root, so I must have ran it with sudo at some point.
The owner of most of the cache files and folders is me, looks like just a couple are root (about 1 in every 100 root owns)

**Comment by bjkomer** [comment]
Could this be because my cache is full, so it is removing the oldest thing, and the oldest thing happened to be created with sudo and is making non-sudo nengo mad?

**Comment by jgosmann** [comment]
Yeah might be. But I don't think it's a nengo bug. If the user runs it with sudo we can't do much about it.

**Comment by tbekolay** [comment]
Yeah. The fix is pretty easy also, in case you haven't already done it:
```bash
sudo chown -R username:group ~/.cache/nengo/decoders 
```
Your username and group should be easy to find is `ls -l` (for me, it's `tbekolay tbekolay` so my invocation would be `sudo chown -R tbekolay:tbekolay ~/.cache/nengo/decoders`)

**Comment by jgosmann** [comment]
Note to self: Verify that cache fails gracefully in these situations and doesn't crash the whole simulation.

**Comment by jgosmann** [comment]
Verified the graceful failure.
