### ISSUE TITLE
Cannot display my vocab due to config

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_gui#439]
When trying to run this simple code testing whether my filtering network is working correctly:
```
import nengo
import nengo.spa as spa
import numpy as np
from nengo.networks import Product
from nengo.networks.workingmemory import InputGatedMemory as WM
from mem_block_basic import MemoryBlock
from nengo.dists import Uniform
from nengo.dists import Choice

# ------------- Network functions --------------

def feature_extract(dimensions, vocab, feature, label="feature extract"):
    """Extract and clean"""
    with nengo.Network(label=label) as net:
        net.input = nengo.Node(size_in=dimensions)
        cleaner = spa.AssociativeMemory(vocab)
        net.output = nengo.Node(size_in=dimensions)

        nengo.Connection(net.input, cleaner.input, transform=((~vocab[feature]).get_convolution_matrix()), synapse=None)
        nengo.Connection(cleaner.output, net.output, synapse=None)

    return net

# ------------- Prameters to use --------------
n_neurons = 500
D = 64
diff_gain = 15

vocab = spa.Vocabulary(D, unitary=True )
vocab.parse('SHAPE')
vocab.parse('COLOR')
vocab.parse('POS')
vocab.parse('LEFT')
vocab.parse('BOTTOM')
vocab.parse('RIGHT')
vocab.parse('SQR')
vocab.parse('TRI')
vocab.parse('CIRC')
vocab.parse('BLUE')
vocab.parse('RED')
vocab.parse('GREEN')

color_vocab = vocab.create_subset(["BLUE", "RED", "GREEN"])
shape_vocab = vocab.create_subset(["SQR", "TRI", "CIRC"])

# updating rules value
positive_rw = 0.2
negative_rw = 0.3

model = spa.SPA()
with model:
	sample_input = spa.Input(sample="SHAPE*SQR+COLOR*RED")
	sample = spa.Buffer(D, vocab)
	shape_extract = feature_extract(D, shape_vocab, "SHAPE", "shape extract")

	nengo.Connection(sample.state.output, shape_extract.input)
```

I get this bizarre error:
```
Traceback (most recent call last):
  File "/home/sean/GitHub-linux/nengo_gui/nengo_gui/swi.py", line 276, in handle_request
    text = getattr(self, command)(*args[1:], **db)
  File "/home/sean/GitHub-linux/nengo_gui/nengo_gui/server.py", line 92, in swi
    viz_sim = self.server.viz.create_sim()
  File "/home/sean/GitHub-linux/nengo_gui/nengo_gui/viz.py", line 411, in create_sim
    viz_sim = VizSim(self)
  File "/home/sean/GitHub-linux/nengo_gui/nengo_gui/viz.py", line 48, in __init__
    self.add_template(template)
  File "/home/sean/GitHub-linux/nengo_gui/nengo_gui/viz.py", line 74, in add_template
    c = template.create(self)
  File "/home/sean/GitHub-linux/nengo_gui/nengo_gui/components/component.py", line 37, in create
    *self.args, **self.kwargs)
  File "/home/sean/GitHub-linux/nengo_gui/nengo_gui/components/pointer.py", line 22, in __init__
    self.vocab_out.include_pairs = config.show_pairs
AttributeError: 'int' object has no attribute 'include_pairs'
```

**Comment by Seanny123** [comment]
While trying to recreate the error, I have determined that this is not a Nengo GUI problem.
