### ISSUE TITLE
Can't start nengo_gui in a cmd window if not on partition C: (Windows)

### ISSUE THREAD

**Issue by pabogdan** [nengo/nengo_gui#486]
Trying to start nengo_gui with not command line arguments used to work fine, and still works if you're on C: but not if you're somewhere else. 

```
D:\Documents\SomeFolder>nengo_gui
:0: FutureWarning: IPython widgets are experimental and may change in the future.
Traceback (most recent call last):
  File "C:\Python27\Scripts\nengo_gui-script.py", line 9, in <module>
    load_entry_point('nengo-gui==0.1.5-dev', 'console_scripts', 'nengo_gui')()
  File "C:\nengo_gui\nengo_gui\main.py", line 29, in main
    backend=args.backend)
  File "C:\nengo_gui\nengo_gui\gui.py", line 64, in __init__
    filename = os.path.relpath(filename)
  File "c:\Python27\lib\ntpath.py", line 528, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive C:, start on drive D:
```

It does, on the other hand, work if you're in D: and you give it a file 
```
nengo_gui some_simulation.py
```

**Comment by tcstewar** [comment]
Ouch.  I hadn't thought about that case at all....   Thank you for finding that bug!

**Comment by pabogdan** [comment]
No problem, it's all for the greater open source good :P. Keep on doing a good job!

**Comment by tcstewar** [comment]
Finally got around to fixing this.  Thanks for poking me about it!  :)
