### ISSUE TITLE
Semantic pointer plot crashes

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_gui#640]
```
Error processing: "{"act":"create_graph","type":"SpaSimilarity","x":0.3727272727272728,"y":0.6579620576207608,"width":0.078125,"height":0.11376564277588168,"uid":"model.stimulus.cue2","args":"default"}"
Traceback (most recent call last):
  File "/Volumes/Home/blubb/Documents/projects/uni/nengo_gui/nengo_gui/server.py", line 136, in ws_viz_component
    component.message(msg)
  File "/Volumes/Home/blubb/Documents/projects/uni/nengo_gui/nengo_gui/components/netgraph.py", line 412, in message
    act = nengo_gui.user_action.create_action(action, self, **info)
  File "/Volumes/Home/blubb/Documents/projects/uni/nengo_gui/nengo_gui/user_action.py", line 14, in create_action
    return CreateGraph(net_graph, **kwargs)
  File "/Volumes/Home/blubb/Documents/projects/uni/nengo_gui/nengo_gui/user_action.py", line 139, in __init__
    self.component = cls(self.obj, **kwargs)
  File "/Volumes/Home/blubb/Documents/projects/uni/nengo_gui/nengo_gui/components/spa_similarity.py", line 18, in __init__
    self.old_vocab_length = len(self.vocab_out.keys)
AttributeError: 'int' object has no attribute 'keys'
```

**Comment by Seanny123** [comment]
Were we able to reproduce this or should this be closed?

**Comment by jgosmann** [comment]
Several SPA modules allow to pass in an `int` as vocab (which declares the dimensionality of the vocab to use). Try to use such a module, pass in an `int` as vocab and try to open the Semantic Pointer plot.

**Comment by jgosmann** [comment]
This is not purely a nengo_gui bug. Potentially there should be a better error message in nengo_gui and it should not fail, but the actual problem is probably related to nengo/nengo#556 because for hierarchical modules the magic converting integers to vocabs does not get called.

I have some trouble thinking of a minimal example because submodules are currently not supported (though I think they should be supported) and I am not sure what the code for a hierarchical module should look like (because it could easily break at a number of other points than just this issue).

**Comment by tcstewar** [comment]
Yup, this is part of the bigger issue of doing submodules in spa.

**Comment by jgosmann** [comment]
Easy way to reproduce the problem without submodules (when forgetting to assign SPA modules to the model or to using `spa.SPA`):
```python
import nengo
from nengo import spa

with nengo.Network() as model:
    s = spa.State(dimensions=16)
```
and try to open the Semantic Pointer plot for s.
