### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_gui#710]
When loading the Nengo GUI (master branch with Nengo master branch), I get the following error:
```
Traceback (most recent call last):
  File "/home/saubin/git/nengo_gui/nengo_gui/server.py", line 142, in ws_viz_component
    component.update_client(client)
  File "/home/saubin/git/nengo_gui/nengo_gui/components/netgraph.py", line 391, in update_client
    self.expand_network(network, client)
  File "/home/saubin/git/nengo_gui/nengo_gui/components/netgraph.py", line 495, in expand_network
    self.page.config[network].expanded = True
  File "/home/saubin/git/nengo/nengo/config.py", line 156, in __setattr__
    self._clsparams.get_param(key).__set__(self, value)
  File "/home/saubin/git/nengo/nengo/params.py", line 81, in __set__
    self.validate(instance, value)
  File "/home/saubin/git/nengo/nengo/params.py", line 113, in validate
    raise ReadonlyError(attr=self.name, obj=instance)
ReadonlyError: InstanceParams.False: False is read-only and cannot be changed
```

**Comment by tcstewar** [comment]
Very weird...  I don't get that at all.  Anyone else getting this?

**Comment by arvoelke** [comment]
Does it depend on the config? i.e. if you try a different network, or delete the config, does this still happen? I'm wondering this because of `self.page.config[network].expanded = True` from the stack trace.

**Comment by Seanny123** [comment]
I tried deleting the config and I got the same result. I also got the same
result by trying another (simpler) network.

**Comment by Seanny123** [comment]
Apparently I wasn't on `master` for Nengo GUI....
