### ISSUE TITLE
windows socket error 10013

### ISSUE THREAD

**Issue by fragapanagos** [nengo/nengo_gui#713]
When trying to start nengo_gui in Windows 10, some students of a class Kwabena is teaching encountered the following error. Is there a work around or fix?

Starting nengo_gui server at http://localhost:8080
Traceback (most recent call last):
  File "c:\users\theUser\anaconda2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\theUser\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\theUser\Anaconda2\Scripts\nengo_gui.exe\__main__.py", line 9, in <module>
  File "c:\users\theUser\anaconda2\lib\site-packages\nengo_gui\main.py", line 34, in main
    s.start(port=args.port, password=args.password, browser=args.browser)
  File "c:\users\theUser\anaconda2\lib\site-packages\nengo_gui\gui.py", line 91, in start
    addr=addr, interactive=self.interactive)
  File "c:\users\theUser\anaconda2\lib\site-packages\nengo_gui\swi.py", line 394, in start
    server = cls.prepare_server(viz, port, asynch, addr, browser)
  File "c:\users\theUser\anaconda2\lib\site-packages\nengo_gui\swi.py", line 401, in prepare_server
    server = AsyncHTTPServer((addr, port), cls)
  File "c:\users\theUser\anaconda2\lib\site-packages\nengo_gui\swi.py", line 491, in __init__
    BaseHTTPServer.HTTPServer.__init__(self, *args, **kwargs)
  File "c:\users\theUser\anaconda2\lib\SocketServer.py", line 420, in __init__
    self.server_bind()
  File "c:\users\theUser\anaconda2\lib\BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "c:\users\theUser\anaconda2\lib\SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "c:\users\theUser\anaconda2\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by tcstewar** [comment]
Ooo... interesting...  looks like windows 10 might have permissions problems with the firewall...  It runs fine on the windows 10 machine here, but it might have different permissions settings.

However, one other thing to try is that maybe something else is using that particular port.  Could you try telling nengo_gui to run on a different port?  @xchoo has run into a similar thing before when something else was running in the background.  Here's the command:

```
nengo_gui --port 8888
````

**Comment by tcstewar** [comment]
This page also suggests maybe trying to run ```nengo_gui.exe``` as Administrator:

**Comment by tcstewar** [comment]
And that same page suggests that maybe an over-zealous virus scanner could be stopping Python from openning the port:

```
McAfee was blocking it for me. I had to allow the program in the access protection rules

Open VirusScan
Right click on Access Protection and choose Properties
Click on "Anti-virus Standard Protection"
Select rule "Prevent mass mailing worms from sending mail" and click edit
Add the application to the Processes to exclude list and click OK
```

**Comment by tcstewar** [comment]
And a third option:  Try telling the firewall to whitelist Python.exe.

Let me know if any of those work!

**Comment by fragapanagos** [comment]
Switching the port number worked! I suspect it's an antivirus program like McAfee doing its thing.
Catching this exception and printing out such suggestions would be helpful.

**Comment by tcstewar** [comment]
Cool!  I definitely think we should handle this error better -- On Linux it gives a nice "Address already in use" error, which is a lot more useful, but apparently on Windows it just goes with this permissions problem thing.  <sigh>
