### ISSUE TITLE
Error when running on spinnaker after converting direct mode ensembles to regular nodes

### ISSUE THREAD

**Issue by bjkomer** [nengo/nengo_gui#720]
This error appears after running the function that converts these ensembles:

replacing <Ensemble (unlabeled) at 0x7ff65dcc67d0>
replacing <Ensemble (unlabeled) at 0x7ff65dcc6850>
replacing <Ensemble (unlabeled) at 0x7ff65dcc68d0>
replacing <Ensemble (unlabeled) at 0x7ff65dcc6ad0>
replacing <Ensemble (unlabeled) at 0x7ff65dcc6c50>
replacing <Ensemble (unlabeled) at 0x7ff65dcc6cd0>
replacing <Ensemble (unlabeled) at 0x7ff65dcc6d50>
Traceback (most recent call last):
  File "/home/bjkomer/nengo_gui/nengo_gui/page.py", line 435, in build
    self.sim = backend.Simulator(self.model)
  File "/home/bjkomer/nengo/nengo/simulator.py", line 108, in __init__
    self.model.build(network)
  File "/home/bjkomer/nengo/nengo/builder/builder.py", line 34, in build
    return Builder.build(self, obj, *args, **kwargs)
  File "/home/bjkomer/nengo/nengo/builder/builder.py", line 79, in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/home/bjkomer/nengo/nengo/builder/network.py", line 72, in build_network
    model.build(conn)
  File "/home/bjkomer/nengo/nengo/builder/builder.py", line 34, in build
    return Builder.build(self, obj, *args, **kwargs)
  File "/home/bjkomer/nengo/nengo/builder/builder.py", line 79, in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/home/bjkomer/nengo/nengo/builder/connection.py", line 147, in build_connection
    model.sig[conn]['in'] = get_prepost_signal(is_pre=True)
  File "/home/bjkomer/nengo/nengo/builder/connection.py", line 139, in get_prepost_signal
    % (conn, 'pre' if is_pre else 'post', target))
ValueError: Building <Connection from <Ensemble (unlabeled) at 0x7ff65dcc6d50> to <Node (unlabeled) at 0x7ff65c43d190>>: the 'pre' object <Ensemble (unlabeled) at 0x7ff65dcc6d50> is not in the model, or has a size of zero.

**Comment by tcstewar** [comment]
can you post a minimal model that causes this error?

**Comment by tcstewar** [comment]
Also, the converting to direct mode thing is really just a helper function for debugging.  If you're running things on nengo_spinnaker, you shouldn't have anything in direct mode, so you shouldn't need this function at all.

**Comment by bjkomer** [comment]
The problem seems to be when there was a plot created for the direct mode ensemble, and then the line is added to convert it to a Node, the original plot is still showing up in the gui, even though the ensemble it came from technically doesn't exist anymore (I was only using Direct mode in my model for making plots from a transform off of an ensemble). Here's a simple example, the problem only occurs if a plot is made:

```
import nengo
import nengo_spinnaker

model=nengo.Network(seed=13)

with model:
    stim = nengo.Node([0])
    a = nengo.Ensemble(100,1)
    b = nengo.Ensemble(100,1, neuron_type=nengo.Direct())
    nengo.Connection(stim,a)
    nengo.Connection(a,b)

model = direct_nodes(model)

nengo_spinnaker.add_spinnaker_params(model.config)
```

**Comment by Seanny123** [comment]
Revisiting this, the problem seems to be that the function `direct_nodes` modifies the model such that it invalidates some plots, which causes an error.

Further investigation is needed to create a minimal amount of code to reproduce this error, but it's definitely a valid concern.
