### ISSUE TITLE
Filename not defined.

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_gui#729]
I'm trying to run a model in gui via `ctn_benchmark` and I'm getting this exception:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/jgosmann/.pyenv/versions/2.7.11/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/jgosmann/.pyenv/versions/2.7.11/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jgosmann/.pyenv/versions/2.7.11/lib/python2.7/site-packages/nengo_gui-0.2.0.dev0-py2.7.egg/nengo_gui/page.py", line 480, in runner
    self.build()
  File "/home/jgosmann/.pyenv/versions/2.7.11/lib/python2.7/site-packages/nengo_gui-0.2.0.dev0-py2.7.egg/nengo_gui/page.py", line 440, in build
    line = nengo_gui.exec_env.determine_line_number()
  File "/home/jgosmann/.pyenv/versions/2.7.11/lib/python2.7/site-packages/nengo_gui-0.2.0.dev0-py2.7.egg/nengo_gui/exec_env.py", line 75, in determine_line_number
    pattern = 'File "%s", line ' % filename
NameError: global name 'filename' is not defined
```
(which seems to hide the actual exception)

**Comment by tcstewar** [comment]
That is very strange....  that line isn't in master:

https://github.com/nengo/nengo_gui/blob/master/nengo_gui/exec_env.py#L75

That was a fairly old bug that was fixed in this commit

https://github.com/nengo/nengo_gui/commit/025a2059bf73f2b2596ac274a751b14a1b975198

**Comment by jgosmann** [comment]
Upgrading nengo_gui helpded.
