### ISSUE TITLE
Error occurs intermittently when running a model

### ISSUE THREAD

**Issue by bjkomer** [nengo/nengo_gui#760]
When trying to run a model, sometimes it gets stuck on the spinning gear (like it is building) but actually an error occurred (shown in the terminal window, but not in the gui error window).

Here's one that showed up for me (haven't been able to reproduce it yet):
```
Created new window in existing browser session.
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/bjkomer/nengo_gui/nengo_gui/page.py", line 480, in runner
    self.build()
  File "/home/bjkomer/nengo_gui/nengo_gui/page.py", line 423, in build
    c.add_nengo_objects(self)
  File "/home/bjkomer/nengo_gui/nengo_gui/components/sim_control.py", line 51, in add_nengo_objects
    with page.model:
AttributeError: __exit__
```

**Comment by astoeckel** [comment]
I ran into this problem with the current master too. Same stacktrace as above, the exception got thrown when clicking the "play" button to run the model.
