### ISSUE TITLE
Small synapses cause value error

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_gui#783]
If you set a really small synapse on a connection, as shown in the code below:
```
import numpy as np
import nengo

t_scale = 1
dt = 0.001

def imp_func(t):
    t_step = t % (1* t_scale)
    if t_step > 0 * t_scale and t_step < 0.5 * t_scale:
        return 1
    else:
        return 0

with nengo.Network() as model:
    in_nd = nengo.Node(imp_func)
    ens = nengo.Ensemble(150, 1)
    out_nd = nengo.Node(size_in=1)

    nengo.Connection(in_nd, ens, synapse=None)
    nengo.Connection(ens, out_nd, synapse=0.0001)
```

You get the following error:
```
Traceback (most recent call last):
  File "/home/sean/git/nengo_gui/nengo_gui/page.py", line 469, in runner
    self.sim.step()
  File "/home/sean/git/nengo/nengo/simulator.py", line 300, in step
    step_fn()
  File "/home/sean/git/nengo/nengo/builder/operator.py", line 716, in step_simpyfunc
    y = fn(t.item(), *args) if t is not None else fn(*args)
  File "/home/sean/git/nengo_gui/nengo_gui/components/value.py", line 68, in gather_data
    self.data.append(self.struct.pack(t, *x))
OverflowError: float too large to pack with f format
```

**Comment by bjkomer** [comment]
Just ran into this today. Interesting observation I noticed, as you go smaller it starts to work again. `0.0001` causes the error, but `0.001` and `0.00001` do not.
