### ISSUE TITLE
Large HTML nodes eventually disconnect

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo_gui#796]
This can be reproduced by running `visualize.py` from the `summerschool2016/v1-lsd` branch on a slow laptop for 1 minute, or a fast desktop if you wait for 30 minutes. It can also be reproduced more easily by increasing the size of the graphs.

If too much data is sent through the socket at each timestep, it will eventually disconnect. In the GUI, the visualizations stop while the simulation continues. Refreshing fixes the problem. The command line gives the following error:

```
Traceback (most recent call last):
  File "c:\users\aaron\ctn\nengo_gui\nengo_gui\server.py", line 142, in ws_viz_c
omponent
    component.update_client(client)
  File "c:\users\aaron\ctn\nengo_gui\nengo_gui\components\htmlview.py", line 37,
 in update_client
    client.write(item)
  File "c:\users\aaron\ctn\nengo_gui\nengo_gui\swi.py", line 696, in write
    self._sendall(data)
  File "c:\users\aaron\ctn\nengo_gui\nengo_gui\swi.py", line 722, in _sendall
    bytes_sent += self.socket.send(data[bytes_sent:])
error: [Errno 10035] A non-blocking socket operation could not be completed imme
diately
(<class 'socket.error'>, error(10053, 'An established connection was aborted by
the software in your host machine'), ['__class__', '__delattr__', '__dict__', '_
_doc__', '__format__', '__getattribute__', '__getitem__', '__getslice__', '__has
h__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__rep
r__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__'
, '__unicode__', '__weakref__', 'args', 'errno', 'filename', 'message', 'strerro
r'])
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 65306)
Traceback (most recent call last):
  File "c:\Users\Aaron\Anaconda\lib\SocketServer.py", line 599, in process_reque
st_thread
    self.finish_request(request, client_address)
  File "c:\Users\Aaron\Anaconda\lib\SocketServer.py", line 334, in finish_reques
t
    self.RequestHandlerClass(request, client_address, self)
  File "c:\Users\Aaron\Anaconda\lib\SocketServer.py", line 655, in __init__
    self.handle()
  File "c:\Users\Aaron\Anaconda\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "c:\Users\Aaron\Anaconda\lib\BaseHTTPServer.py", line 328, in handle_one_
request
    method()
  File "c:\users\aaron\ctn\nengo_gui\nengo_gui\swi.py", line 210, in do_GET
    self.handle_request(args, db)
  File "c:\users\aaron\ctn\nengo_gui\nengo_gui\swi.py", line 252, in handle_requ
est
    self.handle_ws_request(args, db)
  File "c:\users\aaron\ctn\nengo_gui\nengo_gui\swi.py", line 245, in handle_ws_r
equest
    client.close()
  File "c:\users\aaron\ctn\nengo_gui\nengo_gui\swi.py", line 708, in close
    self._sendall(packet)
  File "c:\users\aaron\ctn\nengo_gui\nengo_gui\swi.py", line 722, in _sendall
    bytes_sent += self.socket.send(data[bytes_sent:])
error: [Errno 10053] An established connection was aborted by the software in yo
ur host machine
----------------------------------------
```

I also tested this briefly on release 0.2.0 (41dc4a7), from before server refactoring, and you get the same error.

**Comment by tcstewar** [comment]
Hmm...  yup, if that buffer gets full, I could see that happening.  I think in this case the correct answer is to just catch the error and ignore it -- all that happens is we'll lose a frame in the visualizer.

**Comment by arvoelke** [comment]
I added `print len(self.data)` to `HTMLView.gather_data` and it alternates between 0 and 1 up until the error. Only after the error does the buffer begin to fill up (and will do so indefinitely until restart).

**Comment by jgosmann** [comment]
Can you test this with the `server-refactor` branch? (I'm not really expect this to be magically fixed in that branch, but who knows.)

**Comment by tcstewar** [comment]
> I added print len(self.data) to HTMLView.gather_data and it alternates between 0 and 1 up until the error. Only after the error does the buffer begin to fill up (and will do so indefinitely until restart).

I meant that the actual TCP/IP buffer will start filling up, as I'm just writing tons of data to it.  Even if there's just 1 item in ```self.data```, it might be a very long item, and it's just going to stay there until the web browser gets a chance to read it.  So if we're writing to it faster than it can be read from, it'll eventually fill.  We can then either wait for it to empty, or start throwing out htmlview items....
