### ISSUE TITLE
Unable to run Nengo GUI on Mac

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_gui#807]
On OS X, Nengo GUI refuses to open a browser window to start the GUI. In Chrome, I get the following error:
<img width="1280" alt="screen shot 2016-07-14 at 12 26 10 pm" src="https://cloud.githubusercontent.com/assets/1918825/16853015/6d09f408-49bf-11e6-8f88-1f725e9e9c8e.png">

In Safari, the error is:
![screen shot 2016-07-14 at 12 26 10 pm 2](https://cloud.githubusercontent.com/assets/1918825/16852979/4222c94a-49bf-11e6-810e-a2dcce82baa3.png)

When I try to change `localhost` to `127.0.0.1`, I get the following error, which may or may not be relevant:
```
Starting nengo server at http://localhost:8080
WARNING:nengo_gui.server:Error response (403): Forbidden
Traceback (most recent call last):
  File "/Users/rgao/Documents/fluffypony/nengo_gui-master/nengo_gui/server.py", line 233, in do_GET
    self.handle_upgrade()
  File "/Users/rgao/Documents/fluffypony/nengo_gui-master/nengo_gui/server.py", line 260, in handle_upgrade
    self.upgrade_to_ws()
  File "/Users/rgao/Documents/fluffypony/nengo_gui-master/nengo_gui/server.py", line 282, in upgrade_to_ws
    raise Forbidden()
Forbidden: Forbidden
```

**Comment by parenthetical-e** [comment]
On my computer, I get a different error that might be related.
```
ERROR:nengo_gui.guibackend:Error during websocket communication.                                                                                               │
Traceback (most recent call last):                                                                                                                             │
  File "/Users/type/anaconda/lib/python2.7/site-packages/nengo_gui/guibackend.py", line 223, in ws_default                                                     │
    msg = self.ws.read_frame()                                                                                                                                 │
  File "/Users/type/anaconda/lib/python2.7/site-packages/nengo_gui/server.py", line 363, in read_frame                                                         │
    self._read()                                                                                                                                               │
  File "/Users/type/anaconda/lib/python2.7/site-packages/nengo_gui/server.py", line 344, in _read                                                              │
    self._buf = self._buf + bytearray(self.socket.recv(512))                                                                                                   │
error: [Errno 54] Connection reset by peer                                                                                                                     │
INFO:root:No connections remaining to the nengo_gui server.                                                                                                    │
No connections remaining to the nengo_gui server.                                                                                                              │
Shutting down server...
```

**Comment by celiasmith** [comment]
i only use it on OSX and it's always worked ok for me.  so the question is: what is the difference in our setups.  i wonder if you have something in your 'security' settings that doesn't allow a server?  Found this [here](https://discussions.apple.com/docs/DOC-3083)

In Lion, do the following:

 go to System Preferences > Sharing and enable Web Sharing.

NOTE: There appears to be a bug in Lion for which I haven't found a workaround. If web sharing doesn't start, just keep try

**Comment by Seanny123** [comment]
As an aside from Chris' comment, going back to f5958e5 causes the same error with `localhost`, but switching to `127.0.0.1` seems to resolve the problem.

**Comment by parenthetical-e** [comment]
Using El Cap (10.11.5). I use both a Jupyter and Rstudio server daily. Rolling back to f5958e5 does work fine, so far as I can tell (only ran a brief test).

**Comment by celiasmith** [comment]
i just updated to the latest versions of the gui and core nengo and it works fine :(  (or :) ?) .. i'm on el cap (10.11.5)  as well.  very strange.

**Comment by jgosmann** [comment]
Please check #808. It should fix most of the problems. Not sure what causes @Seanny123's initial problem of `localhost` not working. It might be fixed by adding in IPv6 support, but it might very well persist.
