### ISSUE TITLE
Handle unicode file names

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo_gui#872]
The file browser dies if it tries to show a file or directory that has any characters outside of the 7-bit-ascii range.  The error is:

```
ERROR:nengo_gui.server:Error response
Traceback (most recent call last):
  File "/home/tcstewar/env/test/local/lib/python2.7/site-packages/nengo_gui/server.py", line 235, in do_GET
    self.http_GET()
  File "/home/tcstewar/env/test/local/lib/python2.7/site-packages/nengo_gui/server.py", line 251, in http_GET
    response = getattr(self, command)()
  File "/home/tcstewar/env/test/local/lib/python2.7/site-packages/nengo_gui/guibackend.py", line 92, in auth_checked
    return fn(inst)
  File "/home/tcstewar/env/test/local/lib/python2.7/site-packages/nengo_gui/guibackend.py", line 168, in browse
    ff = os.path.join(path, f).encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2: ordinal not in range(128)
```

This is related to #139 but is a little bit more common.  We should at least gracefully handle this case, even if just by not showing that file or directory.

**Comment by astoeckel** [comment]
IMHO graceful degradation is not an option. As anecdotal evidence, I have dozens of files and folders with characters outside the ASCII plane (e.g. for a long time all my university stuff was in a folder called “Universität” and all my exercises are archived in folders titled “Übungen”). I think this is pretty common.

Filenames should be treated as byte arrays (“bytes”) as long as possible and only decoded/encoded when interacting directly with the user. Especially for the code in question, note the following in the Python documentation for os.listdir:

> path may be a path-like object. If path is of type bytes (directly or indirectly through the PathLike interface), the filenames returned will also be of type bytes; in all other circumstances, they will be of type str.

So just getting rid of all the encodes/decodes in the code fragment in question should do the job.

**Comment by tcstewar** [comment]
> IMHO graceful degradation is not an option.

I definitely agree with you that we need to support this correctly.  There's a long-standing issue about this #139 , but the problem is that it's a relatively complex task to do while supporting both Python 2 and Python 3.  I keep meaning to get around to sorting out all these issues, but then not actually doing so.  

So mostly I meant that graceful degradation would be a good quick thing to implement right now, so that things will at least not fail catastrophically like @tbekolay encountered.  If it does turn out that it's just a matter of getting rid of the encodes/decodes, then yes, let's definitely do that, but my experience with unicode issues is that it hasn't been that simple across Python versions.

**Comment by astoeckel** [comment]
Just had a participant of the summer school running in this issue. This should really be fixed.
