### ISSUE TITLE
Config error prevents GUI from loading

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_gui#900]
I managed to write a Python file which, when opened in the GUI, will produce a blank page with this exception:
```Traceback (most recent call last):
  File "/home/jgosmann/.pyenv/versions/3.5.3/lib/python3.5/site-packages/nengo_gui/server.py", line 235, in do_GET
    self.http_GET()
  File "/home/jgosmann/.pyenv/versions/3.5.3/lib/python3.5/site-packages/nengo_gui/server.py", line 251, in http_GET
    response = getattr(self, command)()
  File "/home/jgosmann/.pyenv/versions/3.5.3/lib/python3.5/site-packages/nengo_gui/guibackend.py", line 92, in auth_checked
    return fn(inst)
  File "/home/jgosmann/.pyenv/versions/3.5.3/lib/python3.5/site-packages/nengo_gui/guibackend.py", line 191, in serve_main
    page = self.server.create_page(filename, reset_cfg=reset_cfg)
  File "/home/jgosmann/.pyenv/versions/3.5.3/lib/python3.5/site-packages/nengo_gui/guibackend.py", line 390, in create_page
    reset_cfg=reset_cfg)
  File "/home/jgosmann/.pyenv/versions/3.5.3/lib/python3.5/site-packages/nengo_gui/page.py", line 110, in __init__
    self.load()
  File "/home/jgosmann/.pyenv/versions/3.5.3/lib/python3.5/site-packages/nengo_gui/page.py", line 172, in load
    self.config = self.load_config()
  File "/home/jgosmann/.pyenv/versions/3.5.3/lib/python3.5/site-packages/nengo_gui/page.py", line 287, in load_config
    config[self.model].pos = (0, 0)
  File "/home/jgosmann/.pyenv/versions/3.5.3/lib/python3.5/site-packages/nengo/config.py", line 201, in __setattr__
    % (key, type(self._configures).__name__))
nengo.exceptions.ConfigError: Cannot configure the built-in parameter 'pos' on an instance of 'Network'. Please set the attribute directly on the object.
```

Config file:
```
_viz_config[model].expanded=True
_viz_config[model].has_layout=True
_viz_config[model.current].pos=(0.5, 0.10869565217391304)
_viz_config[model.current].size=(0.4, 0.08695652173913043)
_viz_config[model.current].expanded=False
_viz_config[model.current].has_layout=False
_viz_config[model.current.diff].expanded=False
_viz_config[model.current.diff].has_layout=False
_viz_config[model.current.diff.state_ensembles].expanded=False
_viz_config[model.current.diff.state_ensembles].has_layout=False
_viz_config[model.current.diff.state_ensembles.networks[0]].expanded=False
_viz_config[model.current.diff.state_ensembles.networks[0]].has_layout=False
_viz_config[model.current.diff.stimuli].expanded=False
_viz_config[model.current.diff.stimuli].has_layout=False
_viz_config[model.current.mem].expanded=False
_viz_config[model.current.mem].has_layout=False
_viz_config[model.current.mem.state_ensembles].expanded=False
_viz_config[model.current.mem.state_ensembles].has_layout=False
_viz_config[model.current.mem.state_ensembles.networks[0]].expanded=False
_viz_config[model.current.mem.state_ensembles.networks[0]].has_layout=False
_viz_config[model.current.mem.stimuli].expanded=False
_viz_config[model.current.mem.stimuli].has_layout=False
_viz_config[model.current.stimuli].expanded=False
_viz_config[model.current.stimuli].has_layout=False
_viz_config[model.last_stim].pos=(0.5, 0.6956521739130435)
_viz_config[model.last_stim].size=(0.4, 0.08695652173913043)
_viz_config[model.last_stim].expanded=False
_viz_config[model.last_stim].has_layout=False
_viz_config[model.last_stim.state_ensembles].expanded=False
_viz_config[model.last_stim.state_ensembles].has_layout=False
_viz_config[model.last_stim.state_ensembles.networks[0]].expanded=False
_viz_config[model.last_stim.state_ensembles.networks[0]].has_layout=False
_viz_config[model.last_stim.stimuli].expanded=False
_viz_config[model.last_stim.stimuli].has_layout=False
_viz_config[model.pos].pos=(0.5, 0.49999999999999994)
_viz_config[model.pos].size=(0.4, 0.08695652173913043)
_viz_config[model.pos].expanded=False
_viz_config[model.pos].has_layout=False
_viz_config[model.pos.state_ensembles].expanded=False
_viz_config[model.pos.state_ensembles].has_layout=False
_viz_config[model.pos.state_ensembles.networks[0]].expanded=False
_viz_config[model.pos.state_ensembles.networks[0]].has_layout=False
_viz_config[model.pos.stimuli].expanded=False
_viz_config[model.pos.stimuli].has_layout=False
_viz_config[model.sim_th].pos=(0.6447477253928868, 0.5365485637643904)
_viz_config[model.sim_th].size=(0.4, 0.08695652173913043)
_viz_config[model.sim_th].expanded=False
_viz_config[model.sim_th].has_layout=False
_viz_config[model.sim_th.dot].expanded=False
_viz_config[model.sim_th.dot].has_layout=False
_viz_config[model.sim_th.dot.product].expanded=False
_viz_config[model.sim_th.dot.product].has_layout=False
_viz_config[model.sim_th.dot.product.sq1].expanded=False
_viz_config[model.sim_th.dot.product.sq1].has_layout=False
_viz_config[model.sim_th.dot.product.sq2].expanded=False
_viz_config[model.sim_th.dot.product.sq2].has_layout=False
_viz_config[model.sim_th.dot.stimuli].expanded=False
_viz_config[model.sim_th.dot.stimuli].has_layout=False
_viz_config[model.sim_th.stimuli].expanded=False
_viz_config[model.sim_th.stimuli].has_layout=False
_viz_config[model.stimuli].expanded=False
_viz_config[model.stimuli].has_layout=False
_viz_config[model.updated].pos=(0.5, 0.3043478260869565)
_viz_config[model.updated].size=(0.4, 0.08695652173913043)
_viz_config[model.updated].expanded=False
_viz_config[model.updated].has_layout=False
_viz_config[model.updated.diff].expanded=False
_viz_config[model.updated.diff].has_layout=False
_viz_config[model.updated.diff.state_ensembles].expanded=False
_viz_config[model.updated.diff.state_ensembles].has_layout=False
_viz_config[model.updated.diff.state_ensembles.networks[0]].expanded=False
_viz_config[model.updated.diff.state_ensembles.networks[0]].has_layout=False
_viz_config[model.updated.diff.stimuli].expanded=False
_viz_config[model.updated.diff.stimuli].has_layout=False
_viz_config[model.updated.mem].expanded=False
_viz_config[model.updated.mem].has_layout=False
_viz_config[model.updated.mem.state_ensembles].expanded=False
_viz_config[model.updated.mem.state_ensembles].has_layout=False
_viz_config[model.updated.mem.state_ensembles.networks[0]].expanded=False
_viz_config[model.updated.mem.state_ensembles.networks[0]].has_layout=False
_viz_config[model.updated.mem.stimuli].expanded=False
_viz_config[model.updated.mem.stimuli].has_layout=False
_viz_config[model.updated.stimuli].expanded=False
_viz_config[model.updated.stimuli].has_layout=False
```

File:
```python
import nengo
import nengo_spa as spa

from imem.modules import GatedMemory, SimilarityThreshold

d = 64

with spa.Network() as model:
    model.vocabs.get_or_create(d).populate('Inc.unitary()')
    
    model.current = GatedMemory(d)
    model.updated = GatedMemory(d)
    nengo.Connection(
        model.current.output, model.updated.input,
        transform=model.vocabs[d]['Inc'].get_convolution_matrix())
    nengo.Connection(model.updated.output, model.current.input)
    
    model.pos = spa.State(d)
    
    model.last_stim = spa.State(d, feedback=1.)
    model.sim_th = SimilarityThreshold(d)
    nengo.Connection(model.pos.output, model.sim_th.input_a)
    nengo.Connection(model.last_stim.output, model.sim_th.input_b)
```

**Comment by jgosmann** [comment]
Note that this happens on both master and with the basic nengo_spa support (#29).

**Comment by tbekolay** [comment]
I believe this occurs because of the line `model.pos = spa.State(d)`, since `pos` is an attribute the Nengo GUI adds to objects; see #562 and issues linked there.
