### ISSUE TITLE
Unhandled ValueError in autocompletion

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo_gui#936]
I'm not sure how to replicate this, but I managed to get this error with the new autocompletion:

```
ERROR:nengo_gui.server:Error response
Traceback (most recent call last):
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\server.py", line 376
, in do_GET
    self.http_GET()
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\server.py", line 392
, in http_GET
    response = getattr(self, command)()
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\guibackend.py", line
 94, in auth_checked
    return fn(inst)
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\guibackend.py", line
 196, in complete
    self.db['filename'])
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\completion.py", line
 19, in get_completions
    return script.completions()
  File "c:\users\terry\py3\lib\site-packages\jedi\api\__init__.py", line 179, in
 completions
    completions = completion.completions()
  File "c:\users\terry\py3\lib\site-packages\jedi\api\completion.py", line 96, i
n completions
    completion_names = self._get_context_completions()
  File "c:\users\terry\py3\lib\site-packages\jedi\api\completion.py", line 175,
in _get_context_completions
    call_signatures = self._call_signatures_method()
  File "c:\users\terry\py3\lib\site-packages\jedi\api\__init__.py", line 305, in
 call_signatures
    helpers.get_call_signature_details(self._get_module_node(), self._pos)
  File "c:\users\terry\py3\lib\site-packages\jedi\api\helpers.py", line 255, in
get_call_signature_details
    leaf = module.get_leaf_for_position(position, include_prefixes=True)
  File "c:\users\terry\py3\lib\site-packages\jedi\parser\tree.py", line 230, in
get_leaf_for_position
    raise ValueError('Please provide a position that exists within this node.')
ValueError: Please provide a position that exists within this node.
Traceback (most recent call last):
  File "C:\Users\Terry\py3\Scripts\nengo-script.py", line 11, in <module>
    load_entry_point('nengo-gui', 'console_scripts', 'nengo')()
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\main.py", line 116,
in main
    s.start()
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\gui.py", line 81, in
 start
    self.server.serve_forever(poll_interval=0.02)
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\server.py", line 200
, in serve_forever
    r, _, _ = select.select(sockets, [], [], poll_interval)
```

My guess is we should have `completion.py` check for an exception there (line 19) and return an empty list.....

**Comment by jgosmann** [comment]
Does this exception actually break the GUI?
What Jedi version do you have installed? My version doesn't have the file that raises the exception.
It seems that for some reason the column and row position doesn't match the provided code ...

**Comment by jgosmann** [comment]
(Just checking for exception hides the symptom, but I would like to understand what problem is at the root of this.)

**Comment by tcstewar** [comment]
> Does this exception actually break the GUI?

Yup.  It becomes unresponsive to saving....  :(

> What Jedi version do you have installed?
```
jedi==0.10.2
```

**Comment by jgosmann** [comment]
Do happen to have the editor content and the position of the cursor of when this error occured?

**Comment by jgosmann** [comment]
Are you sure that this is caused by the autocompletion? When I raise an exception in the `complete` method on purpose, it gets caught, printed to the console, and I can continue to use the GUI. I just don't get any autocompletion. It seems to me that you might have broken the GUI first and because of that the autocompletion also failed. There is also the beginning of a second stack trace in the output you posted that seems to be unrelated to the first stacktrace, but is incomplete and doesn't show the actual exception.
