### ISSUE TITLE
error : must declare a nengo.Network called "model"

### ISSUE THREAD

**Issue by han88** [nengo/nengo_gui#937]
Hi when I run a model from the  htbab_tutorials in the jupyter notebook I get the following error:

i.e.
from nengo_gui.ipython import IPythonViz
IPythonViz(model, "ch1-singleneuron.py.cfg")

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nengo_gui/page.py", line 514, in runner
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/nengo_gui/page.py", line 447, in build
    seeds = nengo_gui.seed_generation.define_all_seeds(self.model)
  File "/usr/local/lib/python2.7/dist-packages/nengo_gui/seed_generation.py", line 10, in define_all_seeds
    if net.seed is None:
AttributeError: 'NoneType' object has no attribute 'seed'

How can i fix this?

**Comment by han88** [comment]
I added the whole path to IPythonViz(model, "/usr/local/..../ch1-singleneuron.py.cfg") and the model is running but there are no plots to see...

**Comment by Seanny123** [comment]
That's definitely not supposed to happen! What versions of Nengo and Nengo GUI are you running?

**Comment by han88** [comment]
Hi i installed the last version (2.6.0). the above mentioned problem occurs only if i start the examples from the jupyter notebook "Run all"). if i start it form the terminal: > nengo /path to/example.py everything works fine...

**Comment by Seanny123** [comment]
Whelp, there's definitely something wrong with the config. I'll try and figure out how to fix this. To get around this, you can run `IPythonViz(model)` and make the plots yourself in the meantime. Sorry about this. We're in the process of refactoring/rewriting the Nengo GUI and we haven't made integrated testing of the examples yet. :/

**Comment by Seanny123** [comment]
It's not the config... It's definitely something in the way we check for models... Dunno how to fix it though.

**Comment by jgosmann** [comment]
This has come up for some people in the summer school and I remember seeing the same error. Restarting the GUI seems to help, but we might want to figure out the cause of this.
