### ISSUE TITLE
Auth token error when instantiating GUI from script

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo_gui#945]
Starting the nengo GUI from script using the code below (which used to work) now throws an error.
Minimal code to reproduce error:
```
import nengo
import nengo_gui

with nengo.Network() as model:
    ens = nengo.Ensemble(50, 1)

nengo_gui.GUI(__file__, model=model, locals=locals(), editor=False).start()
```

The error:
```
Traceback (most recent call last):
  File "run_spaun_probe_data.py", line 403, in <module>
    editor=False).start()
  File "c:\users\xchoo\github\nengo_gui\nengo_gui\gui.py", line 147, in start
    self.server.settings.auth_token,)))
AttributeError: 'GuiServerSettings' object has no attribute 'auth_token'
```

**Comment by tcstewar** [comment]
There's a `fix-gui-launch` branch that should fix this -- can you check if that works for you?

**Comment by xchoo** [comment]
Yup. That works. Throws another error though, here: #946
